export const FETCH_DASHBOARD_DATA = "FETCH_DASHBOARD_DATA";
export const FETCH_LISTING_DATA = "FETCH_LISTING_DATA";
export const USER_CLICKED_DATA = "USER_CLICKED_DATA";
export const SELECTED_SIDENAV_ITEM = "SELECTED_SIDENAV_ITEM";
export const SELECTED_CARD_TITLE = "SELECTED_CARD_TITLE";